import type { Metadata } from 'next';

import Header from '@/components/Header/Header';
import { jakarta } from '@/constants/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jakarta.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
